server:
  port: 8011
  servlet:
    context-path: /consumer-payment

spring:
  application:
    name: luna-consumer-payment-hystrix
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: luna-consumer-payment-openfeign-hystrix-node
    # 访问路径IP显示
    prefer-ip-address: true
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      defaultZone: http://eurekanodei.com:7001/eureka-server/eureka/
      #defaultZone: http://eurekanodeii.com:7002/eureka-server/eureka/,http://eurekanodei.com:7001/eureka-server/eureka/

# Openfeign默认超时等待为一秒，在消费者里面配置超时时间
ribbon:
  # 建立链接后两端的连接时长 默认1秒
  ReadTimeout: 5000
  # 建立链接后从服务器读取的时长 默认1秒
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true  # 在feign中开启 hystrix

#hystrix熔断超时配置
hystrix:
  command:
    default:
      execution:
        #开启超时配置(默认为开启)
        timeout:
          enabled: true
        #设置超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 1500


logging:
  level:
    # feign 日志配置
    com.luna.payment.service.PaymentService: debug